theme: minimal-mistakes-jekyll
minimal_mistakes_skin    : "dirt"
title: [CaTcHcoder
 Blog]
description: []
# Social Sharing
twitter:
  username               : catchcoder
twitter_username: catchcoder
github_username:  catchcoder
email: ji4knw7k0@mozmail.com


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
